# Generated by Django 3.0.5 on 2020-04-03 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='顧客番号')),
                ('name', models.CharField(max_length=200, verbose_name='顧客名')),
                ('adress', models.TextField(max_length=1000, verbose_name='住所')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='商品番号')),
                ('name', models.CharField(max_length=200, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='価格')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='注文番号')),
                ('quantity', models.CharField(max_length=200, verbose_name='数量')),
                ('client_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Client', verbose_name='顧客')),
                ('product_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Product', verbose_name='商品')),
            ],
        ),
    ]
